### PR TITLE
php8 compatibility

### PR DESCRIPTION
**Pull request by alexmontoanelli**
Changes by @jan-e and @wagonza

### CODE REVIEW

**Comment by jozefrebjak** [comment]
@alexmontoanelli  will be this ever merged and available within PHP 8 ?

**Comment by alexmontoanelli** [comment]
@jozefrebjak , i don't thing so.
But we are currently running this version compiled by hand, on our enviroment without issues

**Comment by jozefrebjak** [comment]
Can you help me how to get it workimg ?

**Comment by alexmontoanelli** [comment]
Ensure you have php-dev tools installed, then ..


Clone this, https://github.com/UNETVALE/php-radius
phpize
./configure
make
make install

**Comment by tvdijen** [comment]
@LawnGnome You would make a lot of people happy if you merged this 🙏

**Comment by mbretter** [comment]
superseeded by #9

**Comment by tvdijen** [comment]
Thanks, but I couldn't wait any longer and started using a native PHP-implementation instead.

**Pull request closed without merging**
